version: '3.8'

#NJG-InfoSec: Removed port 22 (SSH)
#NJG-InfoSec: Could not get .yml to pull values for variables from .env file
services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - DATABASE_PASSWORD=super_secret_password_123
      - DATABASE_USERNAME=postgres
      - DATABASE_HOST=postgres
      - DATABASE_NAME=todoapp
      - DEBUG=True
    volumes:
      - /:/host_root:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /etc/passwd:/etc/passwd:ro
      - .:/app:rw
    privileged: true
    user: root
    cap_add:
      - ALL
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    depends_on:
      - postgres
      - redis
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'

#NJG-InfoSec: Updated version of postgres
  postgres:
    image: postgres:18.0
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=super_secret_password_123
      - POSTGRES_DB=todoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    user: root
    command: postgres -c 'log_statement=all' -c 'log_destination=stderr' -c 'log_connections=on' -c 'log_disconnections=on'

#NJG-InfoSec: Updated version of redis
#NJG-InfoSec: Broken Auth by setting password to blank value, could not fix in code
#NJG-InfoSec: Enabled protected mode and allowed access only from localhost
  redis:
    image: redis:8.2.1
    ports:
      - "6379:6379"
    command: redis-server --requirepass "" --protected-mode yes --bind 127.0.0.1
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"